// Finding the artist's own work among everything the iPad backs up.
//
// PicsArt saves to the iPad's camera roll, and Jottacloud's app backs the
// whole roll up — so her pieces arrive mixed in with photographs, screenshots
// and everything else. This picks them out and copies them into the artwork
// folder, using what the files themselves say rather than guessing from
// filenames.
//
// Copying and moving are both offered, and which one is right depends on what
// the source folder is for. A phone backup is meant to hold everything the
// phone has, so copying leaves it intact; a photo library you actually read is
// better off without the artwork mixed in, so moving takes it out. Moving is
// therefore a setting rather than a decision made here — see IntakeConfig.mode.
import {
  walkTree,
  copyFile,
  deleteFile,
  listFolder,
  type MountpointRef,
  type WalkEntry,
} from '@/lib/api'
import { readJsonFile, writeJsonFile } from '@/lib/jsonStore'
import { readArtworkMetadata, type ArtworkFileMetadata } from '@/lib/imageMetadata'

const INTAKE_FOLDER = '.jotta-art-organizer'
const CONFIG_FILENAME = 'intake.json'
const EXAMINED_FILENAME = 'intake-examined.json'
const LOG_FILENAME = 'intake-log.json'

export type FolderRef = MountpointRef & { path: string }

export type IntakeConfig = {
  /** Where the iPad's pictures land — Jottacloud's own photo backup. */
  source: FolderRef
  /** Where her artwork is kept. */
  dest: FolderRef
  enabled: boolean
  /** Whether filing takes the picture out of the source folder as well as
   *  putting it in the destination. Absent means copy, which is what every
   *  setup saved before moving existed. */
  mode?: 'copy' | 'move'
}

export type IntakeMatch = {
  md5: string
  path: string
  name: string
  /** Why this was taken for her work, shown so a wrong guess is visible
   *  rather than mysterious. */
  reason: string
}

export type IntakeScan = {
  matches: IntakeMatch[]
  /** Pictures whose content is already in the destination, yet which are
   *  still sitting in the photo folder — what copying leaves behind, and
   *  what separating the two folders means getting rid of. Only collected
   *  when moving, because copying is the choice to keep both. */
  strays: IntakeMatch[]
  /** Candidates left unexamined because the run hit its budget. Reported so
   *  a partial answer never reads as a complete one. */
  remaining: number
  examined: number
  /** Called off before it finished. What it had already read is kept, but
   *  what it found is not offered — half a look is not an answer. */
  stopped: boolean
  /** The line written to the run log, so the screen can show what it did
   *  without recounting it. Null when the look never got past the walk. */
  logged: IntakeLogEntry | null
}

// PicsArt signs its work in several different places — the editing record it
// leaves in the image description, the program name, the IPTC credit, the
// C2PA claim — and which one you get depends on how the piece was made. A
// drawing carries the working stats; something generated by PicsArt's own AI
// often carries nothing but a signed claim naming it. They are the same tool
// and the same artist, so they are recognised together rather than the
// generated ones falling through to the generic "some AI tool" case.
function namesPicsArt(meta: ArtworkFileMetadata): boolean {
  const said = [meta.programName, meta.credit, meta.sourceType, meta.copyright, ...(meta.authors ?? [])]
  return said.some((value) => typeof value === 'string' && /pics\s*art/i.test(value))
}

// A picture is hers if the file says so. Every one of these is something a
// program wrote about how the image was made — not an inference from the
// picture, and not from its name, which an export can lose.
export function artworkReason(meta: ArtworkFileMetadata | null): string | null {
  if (!meta) return null

  // PicsArt records the editing session in the image description, and its
  // working stats alongside. Nothing else writes these.
  if (meta.editorCreatedAtEpochSeconds != null) return 'PicsArt editing session'
  if (
    meta.editorDrawTimeMs != null ||
    meta.editorPhotosAdded != null ||
    meta.editorLayersUsed != null ||
    meta.editorBrushesUsed != null
  ) {
    return 'PicsArt working stats'
  }
  // Before the generic checks below, so a piece generated in PicsArt is
  // reported as PicsArt rather than as an anonymous content credential.
  if (namesPicsArt(meta)) {
    return meta.sourceType && /algorithmic|generat/i.test(meta.sourceType)
      ? 'Generated in PicsArt'
      : 'Made with PicsArt'
  }

  // C2PA content credentials: a signed claim by the tool that made the file,
  // which is how an AI-generated or AI-edited picture identifies itself.
  if (meta.sourceType) return `Content credentials: ${meta.sourceType}`
  if (meta.credit && /\bai\b|generat/i.test(meta.credit)) return meta.credit

  return null
}

// What each run did, kept in the account rather than on the screen. The
// banner is on the Catalogue's folder-picking screen and disappears the
// moment a folder is chosen, so anything it says about a finished run is
// gone a second later — and a run that copies, removes and describes is
// exactly the sort of thing you want to be able to look up afterwards.
export type IntakeLogEntry = {
  at: string
  kind: 'look' | 'file' | 'tidy'
  /** Absent members didn't apply to that kind of run, rather than being zero. */
  folders?: number
  pictures?: number
  alreadyFiled?: number
  setAside?: number
  read?: number
  found?: number
  remaining?: number
  filed?: number
  removed?: number
  described?: number
  failed?: number
  stopped?: boolean
}

// Enough to answer "what happened last time?" without becoming a file that
// grows forever in an account meant for pictures.
const LOG_LIMIT = 25

export async function loadIntakeLog(metadataLoc: MountpointRef): Promise<IntakeLogEntry[]> {
  const stored = await readJsonFile<{ runs: IntakeLogEntry[] }>(
    metadataLoc,
    `${INTAKE_FOLDER}/${LOG_FILENAME}`
  )
  return stored?.runs ?? []
}

export async function appendIntakeLog(
  metadataLoc: MountpointRef,
  entry: IntakeLogEntry
): Promise<IntakeLogEntry[]> {
  const runs = [entry, ...(await loadIntakeLog(metadataLoc))].slice(0, LOG_LIMIT)
  await writeJsonFile(metadataLoc, INTAKE_FOLDER, LOG_FILENAME, { runs })
  return runs
}

/** One line per run, phrased here so the banner and Setup say the same thing. */
export function summariseRun(entry: IntakeLogEntry): string {
  if (entry.kind === 'look') {
    const parts: string[] = []
    if (entry.pictures != null && entry.folders != null) {
      // The folder count is the point as much as the picture count: it's what
      // shows the look went through everything below the folder, not just it.
      parts.push(
        `${entry.pictures.toLocaleString()} picture${entry.pictures === 1 ? '' : 's'} in ${entry.folders.toLocaleString()} folder${entry.folders === 1 ? '' : 's'}`
      )
    }
    if (entry.alreadyFiled) parts.push(`${entry.alreadyFiled.toLocaleString()} already filed`)
    if (entry.setAside) parts.push(`${entry.setAside.toLocaleString()} set aside before`)
    if (entry.read != null) parts.push(`${entry.read.toLocaleString()} read`)
    parts.push(`${(entry.found ?? 0).toLocaleString()} new to file`)
    if (entry.remaining) parts.push(`${entry.remaining.toLocaleString()} left for next time`)
    return `${entry.stopped ? 'Stopped early — ' : ''}${parts.join(', ')}`
  }
  if (entry.kind === 'file') {
    const parts = [`${(entry.filed ?? 0).toLocaleString()} filed`]
    if (entry.removed) parts.push(`${entry.removed.toLocaleString()} taken out of the photos`)
    if (entry.described) parts.push(`${entry.described.toLocaleString()} described`)
    if (entry.failed) parts.push(`${entry.failed.toLocaleString()} failed`)
    return parts.join(', ')
  }
  const parts = [`${(entry.removed ?? 0).toLocaleString()} already-filed pictures taken out of the photos`]
  if (entry.failed) parts.push(`${entry.failed.toLocaleString()} could not be removed`)
  return parts.join(', ')
}

export async function loadIntakeConfig(metadataLoc: MountpointRef): Promise<IntakeConfig | null> {
  return readJsonFile<IntakeConfig>(metadataLoc, `${INTAKE_FOLDER}/${CONFIG_FILENAME}`)
}

export async function saveIntakeConfig(metadataLoc: MountpointRef, config: IntakeConfig): Promise<void> {
  await writeJsonFile(metadataLoc, INTAKE_FOLDER, CONFIG_FILENAME, config)
}

// Hashes already looked at and found not to be artwork. Without this every
// start would re-read the header of every holiday photo in the backup, which
// is the one genuinely expensive part of the scan. Kept in the account rather
// than on the device so a second device doesn't repeat the work.
async function loadExamined(metadataLoc: MountpointRef): Promise<Set<string>> {
  const stored = await readJsonFile<{ notArtwork: string[] }>(
    metadataLoc,
    `${INTAKE_FOLDER}/${EXAMINED_FILENAME}`
  )
  return new Set(stored?.notArtwork ?? [])
}

async function saveExamined(metadataLoc: MountpointRef, examined: Set<string>): Promise<void> {
  await writeJsonFile(metadataLoc, INTAKE_FOLDER, EXAMINED_FILENAME, {
    notArtwork: [...examined],
  })
}

// Set aside by hand: a picture that carries the marks of her tools but isn't
// work she wants filed — a screenshot of the editor, a photograph she edited
// once. Kept in the same list as the ones the scan rejected, because it means
// exactly the same thing to every later run: don't offer this again.
export async function rememberNotArtwork(metadataLoc: MountpointRef, md5s: string[]): Promise<void> {
  const examined = await loadExamined(metadataLoc)
  for (const md5 of md5s) examined.add(md5)
  await saveExamined(metadataLoc, examined)
}

export async function countNotArtwork(metadataLoc: MountpointRef): Promise<number> {
  return (await loadExamined(metadataLoc)).size
}

// Empties the list, so everything gets looked at again. The way back from a
// "never" pressed by mistake — without it, one tap would be final, and a
// hidden final decision is a bad thing to build.
export async function forgetNotArtwork(metadataLoc: MountpointRef): Promise<void> {
  await saveExamined(metadataLoc, new Set())
}

// Reading a header is one request per file, so a first run over a full camera
// roll is bounded and resumed on the next start rather than made to finish.
const EXAMINE_BUDGET = 300
const EXAMINE_CONCURRENCY = 6

export async function scanIntake(
  metadataLoc: MountpointRef,
  config: IntakeConfig,
  opts?: { onProgress?: (examined: number, total: number) => void; signal?: AbortSignal }
): Promise<IntakeScan> {
  const sourceLoc = { device: config.source.device, mountpoint: config.source.mountpoint }
  const destLoc = { device: config.dest.device, mountpoint: config.dest.mountpoint }

  const [source, dest, examined] = await Promise.all([
    walkTree(sourceLoc, config.source.path, { signal: opts?.signal }),
    walkTree(destLoc, config.dest.path, { signal: opts?.signal }),
    loadExamined(metadataLoc),
  ])

  // Both walks come back partial when they were called off, and a partial
  // listing would name pictures as unfiled that simply weren't reached yet.
  if (opts?.signal?.aborted) {
    return { matches: [], strays: [], remaining: 0, examined: 0, stopped: true, logged: null }
  }

  // Already filed, or already judged not to be hers. Content hashes, so a
  // renamed copy is still recognised as the same picture.
  const alreadyThere = new Set(dest.files.map((f) => f.md5))
  // The rejected ones get added to `examined` as the run goes, so the count
  // for the log is taken before that starts — otherwise this run's work would
  // be reported as something earlier runs had already decided.
  const examinedBefore = new Set(examined)
  const candidates = source.files.filter((f) => !alreadyThere.has(f.md5) && !examined.has(f.md5))

  // No header read needed to know these are hers: the same content is in the
  // artwork folder, which is how it got there. Every earlier run that copied
  // rather than moved left one of these behind, so this is the backlog that
  // stands between "filed" and "separated".
  const strays =
    config.mode === 'move'
      ? source.files
          .filter((f) => alreadyThere.has(f.md5))
          .map((f) => ({
            md5: f.md5,
            path: f.absPath,
            name: f.absPath.split('/').pop() ?? f.md5,
            reason: `Already in ${config.dest.path || config.dest.mountpoint}`,
          }))
      : []

  const batch = candidates.slice(0, EXAMINE_BUDGET)
  const matches: IntakeMatch[] = []
  let done = 0

  let cursor = 0
  async function worker() {
    for (;;) {
      if (opts?.signal?.aborted) return
      const file: WalkEntry | undefined = batch[cursor++]
      if (!file) return
      let reason: string | null = null
      try {
        reason = artworkReason(await readArtworkMetadata(sourceLoc, file.absPath))
      } catch {
        // An unreadable file is left for next time rather than written off:
        // a dropped request says nothing about what the picture is.
        done++
        opts?.onProgress?.(done, batch.length)
        continue
      }
      if (reason) {
        matches.push({
          md5: file.md5,
          path: file.absPath,
          name: file.absPath.split('/').pop() ?? file.md5,
          reason,
        })
      } else {
        examined.add(file.md5)
      }
      done++
      opts?.onProgress?.(done, batch.length)
    }
  }

  await Promise.all(Array.from({ length: EXAMINE_CONCURRENCY }, worker))

  // Saved even when it was called off: every header read is a request that
  // needn't be made again, so stopping costs nothing already spent.
  await saveExamined(metadataLoc, examined).catch(() => {
    // Losing this costs a repeated scan, never a wrong result.
  })

  // A stopped look is still worth recording — knowing it was called off is
  // the difference between "nothing was found" and "nothing was looked at".
  const entry: IntakeLogEntry = {
    at: new Date().toISOString(),
    kind: 'look',
    // The root folder as well as everything under it: walkTree queues each
    // subfolder it meets, so this is the whole tree, however deep.
    folders: source.folderRelPaths.length + 1,
    pictures: source.files.length,
    alreadyFiled: source.files.filter((f) => alreadyThere.has(f.md5)).length,
    setAside: source.files.filter((f) => examinedBefore.has(f.md5)).length,
    read: done,
    found: matches.length,
    remaining: candidates.length - batch.length,
    ...(opts?.signal?.aborted ? { stopped: true } : {}),
  }
  await appendIntakeLog(metadataLoc, entry).catch(() => {
    // A missing line in the log is not worth failing a scan over.
  })

  if (opts?.signal?.aborted) {
    return { matches: [], strays: [], remaining: 0, examined: done, stopped: true, logged: entry }
  }

  return {
    matches,
    strays,
    remaining: candidates.length - batch.length,
    examined: batch.length,
    stopped: false,
    logged: entry,
  }
}

export type IntakeResult = {
  copied: number
  failed: { name: string; error: string }[]
  /** Where each copy landed, so the caller can describe them straight away. */
  copiedPaths: string[]
  /** Originals taken out of the photo folder. Zero unless moving. */
  removed: number
  /** Copied, but the original stayed put — reported apart from a failed copy
   *  because the picture is safely filed and only the tidying went wrong. */
  removeFailed: { name: string; error: string }[]
}

// One at a time: a copy is a server-side operation on Jottacloud's side, and
// a burst of them against a folder being written to is how the earlier copy
// work produced half-written trees.
export async function fileIntake(config: IntakeConfig, matches: IntakeMatch[]): Promise<IntakeResult> {
  const sourceLoc = { device: config.source.device, mountpoint: config.source.mountpoint }
  const destLoc = { device: config.dest.device, mountpoint: config.dest.mountpoint }
  const failed: IntakeResult['failed'] = []
  let copied = 0

  // Names collide across a camera roll — two exports a month apart can share
  // one. Checked against what's actually in the folder, once, rather than
  // trusting the name to be free.
  const existing = new Set(
    (await listFolder(destLoc, config.dest.path).catch(() => null))?.files.map((f) => f.name) ?? []
  )

  const copiedPaths: string[] = []
  const removeFailed: IntakeResult['removeFailed'] = []
  let removed = 0

  for (const match of matches) {
    const name = uniqueName(match.name, existing)
    try {
      // Joined rather than interpolated: a destination at the root of a
      // mountpoint has an empty path, which would otherwise give "/name".
      const destPath = [config.dest.path, name].filter(Boolean).join('/')
      await copyFile(sourceLoc, match.path, destLoc, destPath)
      existing.add(name)
      copiedPaths.push(destPath)
      copied++
    } catch (err) {
      failed.push({ name: match.name, error: err instanceof Error ? err.message : 'Copy failed.' })
      continue
    }
    // Strictly after the copy has succeeded, and skipped entirely when it
    // hasn't: a move that removes first, or removes anyway, is a move that
    // can lose the picture.
    if (config.mode === 'move') {
      try {
        await deleteFile(sourceLoc, match.path)
        removed++
      } catch (err) {
        removeFailed.push({
          name: match.name,
          error: err instanceof Error ? err.message : 'Could not remove the original.',
        })
      }
    }
  }

  return { copied, failed, copiedPaths, removed, removeFailed }
}

/**
 * Takes out of the photo folder the pictures whose content is already in the
 * artwork folder — the ones earlier copying left behind.
 *
 * The destination is walked again first, so nothing is removed on the strength
 * of a listing taken minutes ago: a picture is only taken out of the source
 * once its content has been seen in the destination just now.
 */
export async function removeStrays(
  config: IntakeConfig,
  strays: IntakeMatch[],
  opts?: { onProgress?: (done: number, total: number) => void }
): Promise<{ removed: number; failed: { name: string; error: string }[]; unconfirmed: number }> {
  const sourceLoc = { device: config.source.device, mountpoint: config.source.mountpoint }
  const destLoc = { device: config.dest.device, mountpoint: config.dest.mountpoint }

  const dest = await walkTree(destLoc, config.dest.path)
  const filed = new Set(dest.files.map((f) => f.md5))

  const failed: { name: string; error: string }[] = []
  let removed = 0
  let unconfirmed = 0
  let done = 0

  for (const stray of strays) {
    if (!filed.has(stray.md5)) {
      unconfirmed++
      opts?.onProgress?.(++done, strays.length)
      continue
    }
    try {
      await deleteFile(sourceLoc, stray.path)
      removed++
    } catch (err) {
      failed.push({
        name: stray.name,
        error: err instanceof Error ? err.message : 'Could not remove it.',
      })
    }
    opts?.onProgress?.(++done, strays.length)
  }

  return { removed, failed, unconfirmed }
}

function uniqueName(name: string, taken: Set<string>): string {
  if (!taken.has(name)) return name
  const dot = name.lastIndexOf('.')
  const stem = dot > 0 ? name.slice(0, dot) : name
  const ext = dot > 0 ? name.slice(dot) : ''
  for (let n = 2; ; n++) {
    const candidate = `${stem} (${n})${ext}`
    if (!taken.has(candidate)) return candidate
  }
}
